#!/usr/bin/env bash
# gen-env.sh — Generate derivative .env files from tenants-native.json (the SSOT)
# Usage: ./scripts/gen-env.sh [tenant-id]
# Default tenant: 1hood (the primary/public-facing frontend tenant)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
TENANTS_FILE="$PROJECT_DIR/go-backend/tenants-native.json"
TENANT_ID="${1:-1hood}"

if ! command -v jq &>/dev/null; then
  echo "ERROR: jq required. sudo dnf install jq" >&2
  exit 1
fi

if [[ ! -f "$TENANTS_FILE" ]]; then
  echo "ERROR: $TENANTS_FILE not found" >&2
  exit 1
fi

# Extract the named tenant
TENANT=$(jq -e --arg id "$TENANT_ID" '.[] | select(.id == $id)' "$TENANTS_FILE") || {
  echo "ERROR: tenant '$TENANT_ID' not found in $TENANTS_FILE" >&2
  exit 1
}

FRONTEND_URL=$(echo "$TENANT" | jq -r '.frontend_url')
JWT_SECRET=$(echo "$TENANT" | jq -r '.jwt_secret')

# ── 1. postiz-lite/.env (Next.js build-time) ───────────────────────────────
ENV_FILE="$PROJECT_DIR/.env"
cat > "$ENV_FILE" <<EOF
# AUTO-GENERATED by scripts/gen-env.sh from tenants-native.json (tenant: $TENANT_ID)
# DO NOT EDIT — regenerate: ./scripts/gen-env.sh $TENANT_ID
# SSOT: go-backend/tenants-native.json
NEXT_PUBLIC_BACKEND_URL=${FRONTEND_URL}/api
FRONTEND_URL=${FRONTEND_URL}
BACKEND_INTERNAL_URL=http://127.0.0.1:5000/api
JWT_SECRET=not-used-at-runtime-multi-tenant-reads-from-tenants-native-json
STORAGE_PROVIDER=local
NEXT_PUBLIC_UPLOAD_DIRECTORY=/uploads
NEXT_TELEMETRY_DISABLED=1
NOT_SECURED=false
EOF
echo "  .env                         ← FRONTEND_URL=$FRONTEND_URL"

# ── 2. 1h00d/.env.local SCHEDULER vars (if 1hood tenant) ───────────────────
if [[ "$TENANT_ID" == "1hood" ]]; then
  ONEHOOD_ENV="/home/petros/1h00d/.env.local"
  if [[ -f "$ONEHOOD_ENV" ]]; then
    # Update SCHEDULER_JWT_SECRET in-place if it exists
    if grep -q '^SCHEDULER_JWT_SECRET=' "$ONEHOOD_ENV"; then
      sed -i "s|^SCHEDULER_JWT_SECRET=.*|SCHEDULER_JWT_SECRET=${JWT_SECRET}|" "$ONEHOOD_ENV"
      echo "  1h00d/.env.local             ← SCHEDULER_JWT_SECRET synced"
    fi
  fi
fi

echo "Done. SSOT: $TENANTS_FILE"
